import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import {
  Building2, Users, Home, MapPin, FileText, BarChart3, Smartphone,
  CheckCircle2, ArrowRight, ExternalLink, Star, TrendingUp, Globe,
  MessageSquare, Layers, DollarSign, Key, Search, Bell, ChevronDown
} from 'lucide-react';
import { useState } from 'react';
import Container from '../components/common/Container';
import Button from '../components/common/Button';
import SEO from '../components/common/SEO';
import Breadcrumbs from '../components/common/Breadcrumbs';
import CTASection from '../components/common/CTASection';

/* ─── SEO Schema ─── */
const schema = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      '@type': 'Service',
      '@id': 'https://cybersynap.com/services/real-estate-software-development#service',
      name: 'Real Estate Software Development',
      description: 'Custom real estate software development including property management systems, real estate CRM, chain marketing software, tenant portals, listing management and ERP for property businesses.',
      provider: { '@type': 'Organization', name: 'CyberSynap', url: 'https://cybersynap.com' },
      areaServed: ['IN', 'US', 'GB', 'AE', 'AU', 'SG'],
      serviceType: 'Real Estate Software Development',
      url: 'https://cybersynap.com/services/real-estate-software-development',
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'INR', description: 'Free consultation and live demo' },
    },
    {
      '@type': 'SoftwareApplication',
      name: 'CyberSynap Property Management System',
      applicationCategory: 'BusinessApplication',
      operatingSystem: 'Web, iOS, Android',
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'INR', description: 'Live demo available' },
      provider: { '@type': 'Organization', name: 'CyberSynap' },
      url: 'https://property.cybersynap.com/login',
    },
    {
      '@type': 'FAQPage',
      mainEntity: [
        {
          '@type': 'Question',
          name: 'What real estate software does CyberSynap build?',
          acceptedAnswer: { '@type': 'Answer', text: 'CyberSynap builds property management systems, real estate CRM, chain marketing software, tenant portals, landlord dashboards, listing management platforms, real estate ERP, lead management systems and mobile apps for property agents and developers.' },
        },
        {
          '@type': 'Question',
          name: 'Does CyberSynap offer a live demo of their property management software?',
          acceptedAnswer: { '@type': 'Answer', text: 'Yes. CyberSynap offers a live demo of their property management system at property.cybersynap.com. You can explore all features including property listings, tenant management, lease tracking and financial reporting.' },
        },
        {
          '@type': 'Question',
          name: 'What is chain marketing software for real estate?',
          acceptedAnswer: { '@type': 'Answer', text: 'Chain marketing software for real estate manages multi-level referral and channel partner networks. It tracks leads generated by each partner, calculates commissions across the chain, manages payouts and provides real-time visibility into network performance for real estate developers.' },
        },
        {
          '@type': 'Question',
          name: 'Can CyberSynap build a custom real estate CRM?',
          acceptedAnswer: { '@type': 'Answer', text: 'Yes. CyberSynap specialises in custom real estate CRM development tailored to the sales workflows of property developers, agencies and brokers. Features include lead capture, pipeline management, follow-up automation, site visit tracking and commission management.' },
        },
        {
          '@type': 'Question',
          name: 'How long does it take to build real estate software?',
          acceptedAnswer: { '@type': 'Answer', text: 'A core property management system or CRM typically takes 8–16 weeks depending on scope. More complex platforms with chain marketing modules, tenant portals and mobile apps take 16–24 weeks. CyberSynap provides a detailed project timeline after the discovery phase.' },
        },
      ],
    },
  ],
};

/* ─── Tools / Products ─── */
const tools = [
  {
    icon: Building2,
    color: 'purple',
    title: 'Property Management System',
    desc: 'End-to-end property management — portfolios, units, tenants, leases, maintenance and financials in one platform.',
    features: ['Multi-property portfolio', 'Lease & contract management', 'Maintenance ticketing', 'Financial reporting'],
  },
  {
    icon: Users,
    color: 'pink',
    title: 'Real Estate CRM',
    desc: 'CRM built specifically for real estate — capture leads, track site visits, manage follow-ups and close deals faster.',
    features: ['Lead pipeline management', 'Site visit scheduling', 'Follow-up automation', 'Commission tracking'],
  },
  {
    icon: Layers,
    color: 'purple',
    title: 'Chain Marketing Software',
    desc: 'Manage multi-level channel partner and referral networks. Track commissions, payouts and network performance in real time.',
    features: ['Multi-level partner network', 'Commission calculation', 'Payout management', 'Network analytics'],
  },
  {
    icon: Home,
    color: 'pink',
    title: 'Listing Management Platform',
    desc: 'Centralise and syndicate property listings across portals. Manage availability, pricing, photos and descriptions from one place.',
    features: ['Portal syndication', 'Availability calendar', 'Bulk image management', 'SEO-ready listing pages'],
  },
  {
    icon: Key,
    color: 'purple',
    title: 'Tenant Portal',
    desc: 'A self-service portal for tenants to pay rent, raise maintenance requests, view documents and communicate with management.',
    features: ['Online rent payment', 'Maintenance requests', 'Document centre', 'Lease renewal workflows'],
  },
  {
    icon: FileText,
    color: 'pink',
    title: 'Landlord Dashboard',
    desc: 'Give landlords real-time visibility into their properties — occupancy, income, maintenance and tenant status in one view.',
    features: ['Occupancy tracking', 'Rental income reports', 'Maintenance visibility', 'Document storage'],
  },
  {
    icon: TrendingUp,
    color: 'purple',
    title: 'Real Estate ERP',
    desc: 'Integrated ERP covering procurement, project costs, payroll and financial management for real estate developers and builders.',
    features: ['Project cost management', 'Procurement & vendor', 'Payroll & HR', 'P&L reporting'],
  },
  {
    icon: Smartphone,
    color: 'pink',
    title: 'Agent Mobile App',
    desc: 'A mobile app for property agents to access leads, update pipelines, schedule visits and receive commission notifications on the go.',
    features: ['Lead & deal access', 'GPS property mapping', 'Visit notes & photos', 'Push notifications'],
  },
  {
    icon: Search,
    color: 'purple',
    title: 'Property Search Portal',
    desc: 'Customer-facing property search with filters, map view, virtual tours and enquiry forms — your own branded portal.',
    features: ['Advanced search filters', 'Map-based search', 'Virtual tour integration', 'Enquiry capture'],
  },
];

/* ─── What real estate businesses need ─── */
const needs = [
  'Lead capture from website, portals and referrals',
  'Pipeline management from enquiry to booking',
  'Site visit scheduling and follow-up automation',
  'Channel partner and broker management',
  'Chain marketing and commission tracking',
  'Property listing management across portals',
  'Tenant onboarding and lease management',
  'Online rent collection and receipts',
  'Maintenance request management',
  'Document management and e-signatures',
  'Financial reporting and owner statements',
  'Multi-branch and multi-project visibility',
];

/* ─── Stats ─── */
const stats = [
  { value: '35%', label: 'Faster deal closure with CRM' },
  { value: '60%', label: 'Reduction in admin time' },
  { value: '100%', label: 'Commission accuracy' },
  { value: '3×', label: 'More leads tracked and followed up' },
];

/* ─── Client types ─── */
const clientTypes = [
  { icon: Building2, label: 'Property Developers', desc: 'Project sales, channel partners, chain marketing' },
  { icon: Home, label: 'Real Estate Agencies', desc: 'Lead management, agent CRM, commission tracking' },
  { icon: Key, label: 'Property Managers', desc: 'Tenant management, rent collection, maintenance' },
  { icon: Globe, label: 'Real Estate Portals', desc: 'Listing platforms, search engines, agent directories' },
  { icon: DollarSign, label: 'Property Investors', desc: 'Portfolio dashboards, rental income, ROI reporting' },
  { icon: Users, label: 'Co-working Spaces', desc: 'Space booking, billing, member management' },
];

/* ─── FAQ ─── */
const faqs = [
  {
    q: 'What real estate software does CyberSynap build?',
    a: 'We build property management systems, real estate CRM, chain marketing software, tenant portals, landlord dashboards, listing platforms, real estate ERP and mobile apps for agents and developers. Each solution is built custom to your workflows.',
  },
  {
    q: 'Can I see a live demo of your property management software?',
    a: 'Yes — visit property.cybersynap.com/login to explore our live property management system. You can see listings, tenant records, lease management, financial reports and more without booking anything.',
  },
  {
    q: 'What is chain marketing software for real estate?',
    a: 'Chain marketing software manages multi-level referral and channel partner networks. It tracks leads generated by each partner, calculates commissions across the chain, manages payouts and gives developers real-time visibility into network performance.',
  },
  {
    q: 'How is your real estate CRM different from generic CRMs?',
    a: 'Generic CRMs are not built for real estate. Our CRM includes site visit tracking, property interest tagging, booking workflows, token and payment tracking, and commission management — features a generic CRM cannot match out of the box.',
  },
  {
    q: 'How long does real estate software development take?',
    a: 'A core system (CRM or property management) typically takes 8–16 weeks. Full-featured platforms with chain marketing, tenant portals and mobile apps take 16–24 weeks. We provide a precise timeline after our discovery session.',
  },
];

function FAQItem({ q, a }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="border border-[var(--border)] rounded-2xl overflow-hidden">
      <button
        onClick={() => setOpen(!open)}
        className="w-full text-left flex items-center justify-between gap-4 px-6 py-5 bg-[var(--bg-surface)] hover:bg-[var(--bg-alt)] transition-colors"
      >
        <span className="text-sm font-semibold text-[var(--text-primary)]">{q}</span>
        <ChevronDown size={16} className={`text-purple-500 flex-shrink-0 transition-transform duration-300 ${open ? 'rotate-180' : ''}`} />
      </button>
      {open && (
        <div className="px-6 py-4 bg-[var(--bg-base)]">
          <p className="text-sm text-[var(--text-secondary)] leading-relaxed">{a}</p>
        </div>
      )}
    </div>
  );
}

const colorMap = {
  purple: { bg: 'bg-purple-50', icon: 'text-purple-600', border: 'border-purple-100' },
  pink:   { bg: 'bg-pink-50',   icon: 'text-pink-500',   border: 'border-pink-100' },
};

export default function RealEstateSoftware() {
  return (
    <>
      <SEO
        title="Real Estate Software Development Company — Property Management, CRM & Chain Marketing Software"
        description="CyberSynap builds custom real estate software — property management systems, real estate CRM, chain marketing software, tenant portals and listing platforms. Live demo available. Based in India, serving globally."
        keywords="real estate software development, property management software, real estate CRM, chain marketing software real estate, tenant management software, property management system India, real estate software company, real estate ERP, real estate agent CRM, property portal development, listing management software, real estate software Lucknow"
        canonical="/services/real-estate-software-development"
        schema={schema}
      />

      {/* ─── Hero ─── */}
      <section className="relative bg-[var(--bg-base)] pt-24 lg:pt-32 pb-20 overflow-hidden">
        <div className="absolute -top-40 -right-40 w-[700px] h-[700px] rounded-full blur-[160px] pointer-events-none opacity-20"
          style={{ background: 'radial-gradient(circle, #8B3DFF, transparent 70%)' }} />
        <div className="absolute bottom-0 left-0 w-[400px] h-[400px] rounded-full blur-[120px] pointer-events-none opacity-10"
          style={{ background: 'radial-gradient(circle, #E83E9F, transparent 70%)' }} />

        <Container className="relative">
          <Breadcrumbs items={[
            { label: 'Home', href: '/' },
            { label: 'Services', href: '/services' },
            { label: 'Real Estate Software' },
          ]} />

          <div className="grid lg:grid-cols-2 gap-14 items-center mt-6">
            <motion.div
              initial={{ opacity: 0, y: 24 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6 }}
            >
              <div className="inline-flex items-center gap-2 rounded-full px-4 py-2 mb-5"
                style={{ background: 'rgba(139,61,255,0.08)', border: '1px solid rgba(139,61,255,0.18)' }}>
                <Building2 size={14} className="text-purple-600" />
                <span className="text-xs font-semibold text-purple-700 uppercase tracking-wider">Real Estate Software</span>
              </div>

              <h1 className="text-4xl sm:text-5xl lg:text-6xl font-extrabold text-[var(--text-primary)] leading-tight tracking-tight mb-5">
                Real Estate Software{' '}
                <span style={{ background: 'linear-gradient(135deg, #E83E9F, #8B3DFF)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>
                  Built to Close Deals
                </span>
              </h1>

              <p className="text-lg text-[var(--text-secondary)] leading-relaxed mb-4">
                Custom property management systems, real estate CRM, chain marketing software and tenant portals — built for how the Indian and global property industry actually works.
              </p>
              <p className="text-base text-[var(--text-secondary)] leading-relaxed mb-8">
                Whether you are a developer managing hundreds of units, an agency tracking hundreds of leads or a property manager handling tenant operations — CyberSynap builds software that fits your exact workflow.
              </p>

              <div className="flex flex-wrap gap-3 mb-8">
                <a href="https://property.cybersynap.com/login" target="_blank" rel="noopener noreferrer">
                  <Button size="lg">
                    <ExternalLink size={17} /> Try Live Demo
                  </Button>
                </a>
                <Link to="/contact#consultation">
                  <Button variant="secondary" size="lg">Book a Free Consultation</Button>
                </Link>
              </div>

              <div className="flex flex-wrap gap-4 text-sm text-[var(--text-muted)]">
                {['Property Management', 'Real Estate CRM', 'Chain Marketing', 'Tenant Portal', 'Agent Mobile App'].map((t) => (
                  <div key={t} className="flex items-center gap-1.5">
                    <CheckCircle2 size={14} className="text-purple-500" />
                    {t}
                  </div>
                ))}
              </div>
            </motion.div>

            {/* Right: Stats */}
            <motion.div
              initial={{ opacity: 0, x: 24 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.6, delay: 0.2 }}
              className="grid grid-cols-2 gap-4"
            >
              {stats.map((s, i) => (
                <div key={i} className="bg-[var(--bg-surface)] rounded-2xl border border-[var(--border)] p-6 shadow-[var(--shadow-card)]">
                  <div className="text-3xl font-black mb-1"
                    style={{ background: 'linear-gradient(135deg, #8B3DFF, #E83E9F)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>
                    {s.value}
                  </div>
                  <div className="text-xs text-[var(--text-muted)] leading-snug">{s.label}</div>
                </div>
              ))}

              {/* Demo card */}
              <div className="col-span-2 rounded-2xl p-5 flex items-center justify-between gap-4"
                style={{ background: 'linear-gradient(135deg, #8B3DFF, #E83E9F)' }}>
                <div>
                  <div className="text-white font-bold text-sm mb-0.5">Live Property Demo</div>
                  <div className="text-white/70 text-xs">Explore all features — no sign-up needed</div>
                </div>
                <a href="https://property.cybersynap.com/login" target="_blank" rel="noopener noreferrer"
                  className="flex-shrink-0 bg-white text-purple-700 font-bold text-xs rounded-xl px-4 py-2.5 flex items-center gap-1.5 hover:bg-white/90 transition-colors">
                  Open Demo <ExternalLink size={13} />
                </a>
              </div>
            </motion.div>
          </div>
        </Container>
      </section>

      {/* ─── Software Tools Grid ─── */}
      <section className="py-24 bg-[var(--bg-alt)]">
        <Container>
          <div className="text-center mb-14">
            <div className="inline-flex items-center gap-2 rounded-full px-4 py-2 mb-4"
              style={{ background: 'rgba(139,61,255,0.08)', border: '1px solid rgba(139,61,255,0.18)' }}>
              <span className="text-xs font-semibold text-purple-700 uppercase tracking-wider">Software We Build</span>
            </div>
            <h2 className="text-3xl sm:text-4xl font-extrabold text-[var(--text-primary)] tracking-tight mb-3">
              Every Tool Real Estate Businesses Need
            </h2>
            <p className="text-[var(--text-secondary)] max-w-2xl mx-auto">
              From property management and CRM to chain marketing and tenant portals — we build the complete software stack for real estate companies of every type.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {tools.map((tool, i) => {
              const Icon = tool.icon;
              const c = colorMap[tool.color];
              return (
                <motion.div
                  key={tool.title}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.4, delay: i * 0.06 }}
                  className="bg-[var(--bg-surface)] rounded-2xl border border-[var(--border)] p-6 hover:border-purple-200 hover:shadow-[var(--shadow-card-hover)] hover:-translate-y-1 transition-all duration-300"
                >
                  <div className={`w-12 h-12 rounded-2xl ${c.bg} border ${c.border} flex items-center justify-center mb-4`}>
                    <Icon size={22} className={c.icon} strokeWidth={1.75} />
                  </div>
                  <h3 className="text-base font-bold text-[var(--text-primary)] mb-2">{tool.title}</h3>
                  <p className="text-sm text-[var(--text-secondary)] leading-relaxed mb-4">{tool.desc}</p>
                  <ul className="space-y-1.5">
                    {tool.features.map((f) => (
                      <li key={f} className="flex items-center gap-2 text-xs text-[var(--text-muted)]">
                        <CheckCircle2 size={12} className="text-purple-400 flex-shrink-0" />
                        {f}
                      </li>
                    ))}
                  </ul>
                </motion.div>
              );
            })}
          </div>
        </Container>
      </section>

      {/* ─── Chain Marketing Deep Dive ─── */}
      <section className="py-24 bg-[var(--bg-base)]">
        <Container>
          <div className="grid lg:grid-cols-2 gap-14 items-center">
            <motion.div
              initial={{ opacity: 0, x: -24 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
            >
              <div className="inline-flex items-center gap-2 rounded-full px-4 py-2 mb-5"
                style={{ background: 'rgba(232,62,159,0.08)', border: '1px solid rgba(232,62,159,0.18)' }}>
                <Layers size={14} className="text-pink-500" />
                <span className="text-xs font-semibold text-pink-600 uppercase tracking-wider">Chain Marketing Software</span>
              </div>
              <h2 className="text-3xl sm:text-4xl font-extrabold text-[var(--text-primary)] tracking-tight mb-4">
                Manage Your Entire Channel Partner Network — Automatically
              </h2>
              <p className="text-[var(--text-secondary)] leading-relaxed mb-6">
                Real estate developers rely on channel partners, brokers and referral networks to generate sales. Our chain marketing software tracks every lead from source to sale, calculates commissions across multi-level networks and automates payouts — eliminating the spreadsheet chaos that slows projects down.
              </p>
              <ul className="space-y-3 mb-8">
                {[
                  'Multi-level partner hierarchy (CP → sub-CP → referral)',
                  'Automatic lead attribution to the correct partner',
                  'Commission slab configuration per project or unit type',
                  'Real-time commission statements for partners',
                  'Payout approval workflow and bank transfer integration',
                  'Partner performance dashboard and leaderboard',
                  'Token and booking amount tracking',
                  'Mobile app for channel partners to track their leads',
                ].map((f) => (
                  <li key={f} className="flex items-start gap-3 text-sm text-[var(--text-secondary)]">
                    <CheckCircle2 size={16} className="text-pink-500 flex-shrink-0 mt-0.5" />
                    {f}
                  </li>
                ))}
              </ul>
              <Link to="/contact#consultation">
                <Button>Discuss Chain Marketing Requirements <ArrowRight size={16} /></Button>
              </Link>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, x: 24 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: 0.15 }}
              className="bg-[var(--bg-surface)] rounded-3xl border border-[var(--border)] p-8 shadow-[var(--shadow-card)]"
            >
              <h3 className="text-base font-bold text-[var(--text-primary)] mb-6">How It Works</h3>
              {[
                { step: '01', title: 'Partner Registers', desc: 'Channel partners register via portal or mobile app and get assigned to their hierarchy level.' },
                { step: '02', title: 'Lead is Submitted', desc: 'Partner submits lead with customer details. System auto-attributes to that partner.' },
                { step: '03', title: 'Lead Converts', desc: 'Sales team converts the lead. Booking and token amounts are logged against the unit.' },
                { step: '04', title: 'Commission Calculated', desc: 'Software calculates commission per slab, across all levels in the chain, instantly.' },
                { step: '05', title: 'Payout Processed', desc: 'Finance approves and releases payout. Partner sees statement in real time.' },
              ].map((s) => (
                <div key={s.step} className="flex gap-4 mb-5 last:mb-0">
                  <div className="w-9 h-9 rounded-full flex-shrink-0 flex items-center justify-center text-white text-xs font-black"
                    style={{ background: 'linear-gradient(135deg, #E83E9F, #8B3DFF)' }}>
                    {s.step}
                  </div>
                  <div>
                    <div className="text-sm font-bold text-[var(--text-primary)] mb-0.5">{s.title}</div>
                    <div className="text-xs text-[var(--text-muted)] leading-relaxed">{s.desc}</div>
                  </div>
                </div>
              ))}
            </motion.div>
          </div>
        </Container>
      </section>

      {/* ─── What Real Estate Businesses Need ─── */}
      <section className="py-24 bg-[var(--bg-alt)]">
        <Container>
          <div className="grid lg:grid-cols-2 gap-14 items-center">
            <div>
              <div className="inline-flex items-center gap-2 rounded-full px-4 py-2 mb-5"
                style={{ background: 'rgba(139,61,255,0.08)', border: '1px solid rgba(139,61,255,0.18)' }}>
                <span className="text-xs font-semibold text-purple-700 uppercase tracking-wider">Requirements Checklist</span>
              </div>
              <h2 className="text-3xl sm:text-4xl font-extrabold text-[var(--text-primary)] tracking-tight mb-4">
                Everything Your Real Estate Business Needs — In One Platform
              </h2>
              <p className="text-[var(--text-secondary)] leading-relaxed mb-8">
                Most real estate companies patch together 5–8 disconnected tools. We build one unified system that covers every operational requirement.
              </p>
              <a href="https://property.cybersynap.com/login" target="_blank" rel="noopener noreferrer">
                <Button>
                  <ExternalLink size={16} /> Explore Live Demo
                </Button>
              </a>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {needs.map((need) => (
                <div key={need} className="flex items-start gap-3 bg-[var(--bg-surface)] rounded-xl border border-[var(--border)] px-4 py-3">
                  <CheckCircle2 size={15} className="text-purple-500 flex-shrink-0 mt-0.5" />
                  <span className="text-sm text-[var(--text-secondary)]">{need}</span>
                </div>
              ))}
            </div>
          </div>
        </Container>
      </section>

      {/* ─── Who We Serve ─── */}
      <section className="py-24 bg-[var(--bg-base)]">
        <Container>
          <div className="text-center mb-12">
            <h2 className="text-3xl font-extrabold text-[var(--text-primary)] tracking-tight mb-3">
              Who We Build For
            </h2>
            <p className="text-[var(--text-secondary)] max-w-xl mx-auto">
              Our real estate software serves every type of property business — from developers to agents to property managers.
            </p>
          </div>
          <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
            {clientTypes.map((ct, i) => {
              const Icon = ct.icon;
              return (
                <motion.div
                  key={ct.label}
                  initial={{ opacity: 0, y: 16 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.4, delay: i * 0.06 }}
                  className="bg-[var(--bg-surface)] rounded-2xl border border-[var(--border)] p-5 text-center"
                >
                  <div className="w-12 h-12 rounded-2xl bg-purple-50 border border-purple-100 flex items-center justify-center mx-auto mb-3">
                    <Icon size={20} className="text-purple-600" strokeWidth={1.75} />
                  </div>
                  <h3 className="text-sm font-bold text-[var(--text-primary)] mb-1">{ct.label}</h3>
                  <p className="text-xs text-[var(--text-muted)]">{ct.desc}</p>
                </motion.div>
              );
            })}
          </div>
        </Container>
      </section>

      {/* ─── Live Demo Banner ─── */}
      <section className="py-16 bg-[var(--bg-alt)]">
        <Container>
          <div className="rounded-3xl p-8 md:p-12 flex flex-col md:flex-row items-center justify-between gap-6"
            style={{ background: 'linear-gradient(135deg, #1a0533, #2d0a5e)', border: '1px solid rgba(139,61,255,0.25)' }}>
            <div>
              <div className="text-xs font-semibold text-purple-400 uppercase tracking-wider mb-2">No sign-up required</div>
              <h2 className="text-2xl sm:text-3xl font-extrabold text-white mb-2">
                Try Our Property Management System Live
              </h2>
              <p className="text-white/60 text-sm max-w-lg">
                Explore property listings, tenant records, lease management, financial reports and chain marketing dashboards — all in a working demo environment.
              </p>
            </div>
            <div className="flex flex-col sm:flex-row gap-3 flex-shrink-0">
              <a href="https://property.cybersynap.com/login" target="_blank" rel="noopener noreferrer"
                className="inline-flex items-center gap-2 px-6 py-3 rounded-xl font-bold text-white text-sm transition-opacity hover:opacity-90"
                style={{ background: 'linear-gradient(135deg, #E83E9F, #8B3DFF)' }}>
                <ExternalLink size={16} /> Open Live Demo
              </a>
              <Link to="/contact#consultation"
                className="inline-flex items-center gap-2 px-6 py-3 rounded-xl font-bold text-white text-sm border border-white/20 hover:bg-white/10 transition-colors">
                Book a Consultation <ArrowRight size={16} />
              </Link>
            </div>
          </div>
        </Container>
      </section>

      {/* ─── Tech Stack ─── */}
      <section className="py-16 bg-[var(--bg-base)]">
        <Container>
          <div className="text-center mb-8">
            <h2 className="text-2xl font-bold text-[var(--text-primary)]">Technology We Use</h2>
          </div>
          <div className="flex flex-wrap justify-center gap-3">
            {['React', 'Node.js', 'Python', 'PostgreSQL', 'MongoDB', 'AWS', 'Google Maps API', 'Stripe', 'Razorpay', 'Twilio', 'SendGrid', 'Docker', 'Redis', 'Next.js', 'React Native'].map((tech) => (
              <span key={tech} className="px-4 py-2 bg-[var(--bg-surface)] rounded-full border border-[var(--border)] text-sm font-medium text-[var(--text-secondary)]">
                {tech}
              </span>
            ))}
          </div>
        </Container>
      </section>

      {/* ─── FAQ ─── */}
      <section className="py-24 bg-[var(--bg-alt)]">
        <Container>
          <div className="max-w-3xl mx-auto">
            <div className="text-center mb-12">
              <h2 className="text-3xl font-extrabold text-[var(--text-primary)] tracking-tight mb-3">
                Frequently Asked Questions
              </h2>
              <p className="text-[var(--text-secondary)]">
                Common questions about our real estate software development services.
              </p>
            </div>
            <div className="space-y-3">
              {faqs.map((faq) => (
                <FAQItem key={faq.q} q={faq.q} a={faq.a} />
              ))}
            </div>
          </div>
        </Container>
      </section>

      <CTASection
        title="Ready to Build Your Real Estate Software?"
        description="Tell us what you need — property management, CRM, chain marketing or a full platform. We will design and build it around your exact business."
        primaryLabel="Start the Conversation"
        primaryHref="/contact"
        secondaryLabel="See Case Studies"
        secondaryHref="/case-studies"
      />
    </>
  );
}
